-- Attendance Module Database Migration
-- Version: 1.0.0

-- Attendance Rule Table
CREATE TABLE IF NOT EXISTS `attendance_rule` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `rule_name` varchar(100) NOT NULL COMMENT 'Rule name',
  `rule_code` varchar(50) NOT NULL COMMENT 'Rule code',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT 'Status: 0-Disabled, 1-Enabled',
  `work_start_time` time DEFAULT NULL COMMENT 'Work start time',
  `work_end_time` time DEFAULT NULL COMMENT 'Work end time',
  `allow_late_minutes` int DEFAULT '0' COMMENT 'Allow late minutes',
  `allow_leave_early_minutes` int DEFAULT '0' COMMENT 'Allow leave early minutes',
  `overtime_rule` tinyint DEFAULT '0' COMMENT 'Overtime rule: 0-No, 1-After work, 2-Fixed',
  `overtime_start_time` time DEFAULT NULL COMMENT 'Overtime start time',
  `min_overtime_duration` int DEFAULT '60' COMMENT 'Minimum overtime duration (minutes)',
  `flexible_work` tinyint DEFAULT '0' COMMENT 'Is flexible work: 0-No, 1-Yes',
  `flexible_work_hours` decimal(4,1) DEFAULT '8.0' COMMENT 'Flexible work hours',
  `include_rest_days` tinyint DEFAULT '0' COMMENT 'Include rest days: 0-No, 1-Yes',
  `weekdays` text COMMENT 'Weekdays to apply (JSON array)',
  `exclude_holidays` text COMMENT 'Holidays to exclude (JSON array)',
  `special_work_days` text COMMENT 'Special work days (JSON array)',
  `dept_ids` text COMMENT 'Applicable department IDs (JSON array)',
  `position_ids` text COMMENT 'Applicable position IDs (JSON array)',
  `timezone` varchar(50) DEFAULT 'Asia/Shanghai' COMMENT 'Timezone',
  `remark` varchar(500) DEFAULT NULL COMMENT 'Remark',
  `deleted` tinyint DEFAULT '0' COMMENT 'Soft delete: 0-Normal, 1-Deleted',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_rule_code` (`rule_code`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Attendance Rule Table';

-- Attendance Group Table
CREATE TABLE IF NOT EXISTS `attendance_group` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `group_name` varchar(100) NOT NULL COMMENT 'Group name',
  `group_code` varchar(50) NOT NULL COMMENT 'Group code',
  `status` tinyint NOT NULL DEFAULT '1' COMMENT 'Status: 0-Disabled, 1-Enabled',
  `rule_id` bigint NOT NULL COMMENT 'Rule ID',
  `schedule_type` tinyint DEFAULT '0' COMMENT 'Schedule type: 0-Normal, 1-Rotating, 2-Flexible',
  `schedule_data` text COMMENT 'Schedule data (JSON)',
  `manager_id` varchar(50) DEFAULT NULL COMMENT 'Manager user ID',
  `manager_name` varchar(100) DEFAULT NULL COMMENT 'Manager name',
  `dept_ids` text COMMENT 'Department IDs (JSON array)',
  `position_ids` text COMMENT 'Position IDs (JSON array)',
  `user_ids` text COMMENT 'User IDs (JSON array)',
  `checkin_locations` text COMMENT 'Check-in locations (JSON array)',
  `wifi_list` text COMMENT 'WiFi list (JSON array)',
  `allow_remote` tinyint DEFAULT '0' COMMENT 'Allow remote check-in: 0-No, 1-Yes',
  `max_remote_distance` int DEFAULT '1000' COMMENT 'Maximum remote distance (meters)',
  `remark` varchar(500) DEFAULT NULL COMMENT 'Remark',
  `deleted` tinyint DEFAULT '0' COMMENT 'Soft delete: 0-Normal, 1-Deleted',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_group_code` (`group_code`),
  KEY `idx_rule_id` (`rule_id`),
  KEY `idx_status` (`status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Attendance Group Table';

-- Attendance Record Table
CREATE TABLE IF NOT EXISTS `attendance_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `user_id` varchar(50) NOT NULL COMMENT 'User ID',
  `user_name` varchar(100) NOT NULL COMMENT 'User name',
  `attendance_date` date NOT NULL COMMENT 'Attendance date',
  `group_id` bigint DEFAULT NULL COMMENT 'Group ID',
  `rule_id` bigint DEFAULT NULL COMMENT 'Rule ID',
  `checkin_time` datetime DEFAULT NULL COMMENT 'Check-in time',
  `checkout_time` datetime DEFAULT NULL COMMENT 'Check-out time',
  `checkin_latitude` decimal(10,8) DEFAULT NULL COMMENT 'Check-in latitude',
  `checkin_longitude` decimal(11,8) DEFAULT NULL COMMENT 'Check-in longitude',
  `checkout_latitude` decimal(10,8) DEFAULT NULL COMMENT 'Check-out latitude',
  `checkout_longitude` decimal(11,8) DEFAULT NULL COMMENT 'Check-out longitude',
  `checkin_address` varchar(500) DEFAULT NULL COMMENT 'Check-in address',
  `checkout_address` varchar(500) DEFAULT NULL COMMENT 'Check-out address',
  `checkin_wifi_mac` varchar(50) DEFAULT NULL COMMENT 'Check-in WiFi MAC',
  `checkout_wifi_mac` varchar(50) DEFAULT NULL COMMENT 'Check-out WiFi MAC',
  `checkin_device_id` varchar(100) DEFAULT NULL COMMENT 'Check-in device ID',
  `checkout_device_id` varchar(100) DEFAULT NULL COMMENT 'Check-out device ID',
  `checkin_ip` varchar(50) DEFAULT NULL COMMENT 'Check-in IP address',
  `checkout_ip` varchar(50) DEFAULT NULL COMMENT 'Check-out IP address',
  `checkin_method` tinyint DEFAULT '0' COMMENT 'Check-in method: 0-GPS, 1-WiFi, 2-Manual, 3-Remote',
  `checkout_method` tinyint DEFAULT '0' COMMENT 'Check-out method: 0-GPS, 1-WiFi, 2-Manual, 3-Remote',
  `status` tinyint DEFAULT '0' COMMENT 'Status: 0-Normal, 1-Late, 2-Leave early, 3-Absent, 4-Overtime, 5-On leave, 6-On business trip',
  `late_minutes` int DEFAULT '0' COMMENT 'Late minutes',
  `leave_early_minutes` int DEFAULT '0' COMMENT 'Leave early minutes',
  `overtime_minutes` int DEFAULT '0' COMMENT 'Overtime minutes',
  `work_hours` decimal(5,2) DEFAULT '0.00' COMMENT 'Work hours',
  `should_work_hours` decimal(5,2) DEFAULT '8.00' COMMENT 'Should work hours',
  `abnormal` tinyint DEFAULT '0' COMMENT 'Is abnormal: 0-No, 1-Yes',
  `abnormal_reason` varchar(500) DEFAULT NULL COMMENT 'Abnormal reason',
  `approval_id` bigint DEFAULT NULL COMMENT 'Approval ID',
  `remark` varchar(500) DEFAULT NULL COMMENT 'Remark',
  `deleted` tinyint DEFAULT '0' COMMENT 'Soft delete: 0-Normal, 1-Deleted',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_date` (`user_id`, `attendance_date`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_attendance_date` (`attendance_date`),
  KEY `idx_group_id` (`group_id`),
  KEY `idx_status` (`status`),
  KEY `idx_checkin_time` (`checkin_time`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Attendance Record Table';

-- Attendance Exception Table
CREATE TABLE IF NOT EXISTS `attendance_exception` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `user_id` varchar(50) NOT NULL COMMENT 'User ID',
  `user_name` varchar(100) NOT NULL COMMENT 'User name',
  `type` tinyint NOT NULL COMMENT 'Application type: 0-Makeup card, 1-Leave, 2-Business trip, 3-Other',
  `application_date` date NOT NULL COMMENT 'Application date',
  `start_time` datetime NOT NULL COMMENT 'Start time',
  `end_time` datetime NOT NULL COMMENT 'End time',
  `reason` text NOT NULL COMMENT 'Reason',
  `attachments` text COMMENT 'Attachment URLs (JSON array)',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT 'Status: 0-Pending, 1-Approved, 2-Rejected, 3-Canceled',
  `approval_id` bigint DEFAULT NULL COMMENT 'Approval ID',
  `approver_id` varchar(50) DEFAULT NULL COMMENT 'Approver ID',
  `approver_name` varchar(100) DEFAULT NULL COMMENT 'Approver name',
  `approval_time` datetime DEFAULT NULL COMMENT 'Approval time',
  `approval_comment` varchar(500) DEFAULT NULL COMMENT 'Approval comment',
  `related_record_ids` text COMMENT 'Related record IDs (JSON array)',
  `dept_id` varchar(50) DEFAULT NULL COMMENT 'Department ID',
  `dept_name` varchar(100) DEFAULT NULL COMMENT 'Department name',
  `process_result` tinyint DEFAULT '0' COMMENT 'Process result: 0-Not processed, 1-Processed, 2-Error',
  `process_message` varchar(500) DEFAULT NULL COMMENT 'Process message',
  `process_time` datetime DEFAULT NULL COMMENT 'Process time',
  `remark` varchar(500) DEFAULT NULL COMMENT 'Remark',
  `deleted` tinyint DEFAULT '0' COMMENT 'Soft delete: 0-Normal, 1-Deleted',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_status` (`status`),
  KEY `idx_application_date` (`application_date`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Attendance Exception Table';

-- Attendance Statistics Table
CREATE TABLE IF NOT EXISTS `attendance_stat` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  `user_id` varchar(50) NOT NULL COMMENT 'User ID',
  `user_name` varchar(100) NOT NULL COMMENT 'User name',
  `stat_date` date NOT NULL COMMENT 'Statistics date',
  `stat_type` tinyint NOT NULL COMMENT 'Statistics type: 0-Daily, 1-Weekly, 2-Monthly, 3-Quarterly, 4-Yearly',
  `total_days` int DEFAULT '0' COMMENT 'Total days',
  `work_days` int DEFAULT '0' COMMENT 'Work days',
  `normal_days` int DEFAULT '0' COMMENT 'Normal days',
  `late_days` int DEFAULT '0' COMMENT 'Late days',
  `leave_early_days` int DEFAULT '0' COMMENT 'Leave early days',
  `absent_days` int DEFAULT '0' COMMENT 'Absent days',
  `overtime_days` int DEFAULT '0' COMMENT 'Overtime days',
  `total_late_minutes` int DEFAULT '0' COMMENT 'Total late minutes',
  `total_leave_early_minutes` int DEFAULT '0' COMMENT 'Total leave early minutes',
  `total_overtime_minutes` int DEFAULT '0' COMMENT 'Total overtime minutes',
  `total_work_hours` decimal(10,2) DEFAULT '0.00' COMMENT 'Total work hours',
  `attendance_score` decimal(5,2) DEFAULT '100.00' COMMENT 'Attendance score',
  `normal_rate` decimal(5,2) DEFAULT '100.00' COMMENT 'Normal rate',
  `deleted` tinyint DEFAULT '0' COMMENT 'Soft delete: 0-Normal, 1-Deleted',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_stat` (`user_id`, `stat_date`, `stat_type`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_stat_date` (`stat_date`),
  KEY `idx_stat_type` (`stat_type`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Attendance Statistics Table';

-- Insert default attendance rules
INSERT INTO `attendance_rule` (`rule_name`, `rule_code`, `status`, `work_start_time`, `work_end_time`, `allow_late_minutes`, `allow_leave_early_minutes`, `overtime_rule`, `flexible_work`, `include_rest_days`, `weekdays`, `timezone`, `remark`) VALUES
('标准考勤规则', 'STANDARD_RULE', 1, '09:00:00', '18:00:00', 10, 10, 1, 0, 0, '[1,2,3,4,5]', 'Asia/Shanghai', '标准工作日考勤规则'),
('弹性考勤规则', 'FLEXIBLE_RULE', 1, NULL, NULL, 30, 30, 0, 1, 0, '[1,2,3,4,5]', 'Asia/Shanghai', '弹性工作时间考勤规则');

-- Insert default attendance groups
INSERT INTO `attendance_group` (`group_name`, `group_code`, `status`, `rule_id`, `schedule_type`, `manager_id`, `manager_name`, `allow_remote`, `max_remote_distance`, `remark`) VALUES
('默认考勤组', 'DEFAULT_GROUP', 1, 1, 0, 'admin', '管理员', 1, 1000, '默认考勤组');