-- Attendance module database schema
-- Version: 2024-04-25

-- Attendance rule table
CREATE TABLE IF NOT EXISTS `attendance_rule` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    `rule_name` varchar(100) NOT NULL COMMENT 'Rule name',
    `rule_code` varchar(50) NOT NULL COMMENT 'Rule code',
    `status` tinyint NOT NULL DEFAULT '1' COMMENT 'Status: 0-Disabled, 1-Enabled',
    `work_start_time` time DEFAULT NULL COMMENT 'Work start time',
    `work_end_time` time DEFAULT NULL COMMENT 'Work end time',
    `allow_late_minutes` int DEFAULT '15' COMMENT 'Allow late minutes',
    `allow_leave_early_minutes` int DEFAULT '15' COMMENT 'Allow leave early minutes',
    `overtime_rule` tinyint DEFAULT '1' COMMENT 'Overtime rule: 0-No overtime, 1-Calculate after work time, 2-Fixed overtime',
    `overtime_start_time` time DEFAULT NULL COMMENT 'Overtime start time',
    `min_overtime_duration` int DEFAULT '30' COMMENT 'Minimum overtime duration (minutes)',
    `flexible_work` tinyint DEFAULT '0' COMMENT 'Is flexible work time: 0-No, 1-Yes',
    `flexible_work_hours` decimal(5,2) DEFAULT '8.00' COMMENT 'Flexible work duration (hours)',
    `include_rest_days` tinyint DEFAULT '0' COMMENT 'Is rest day included: 0-No, 1-Yes',
    `weekdays` json DEFAULT NULL COMMENT 'Weekdays to apply (JSON array)',
    `exclude_holidays` json DEFAULT NULL COMMENT 'Holidays to exclude (JSON array)',
    `special_work_days` json DEFAULT NULL COMMENT 'Special work days (JSON array)',
    `dept_ids` json DEFAULT NULL COMMENT 'Applicable department IDs (JSON array)',
    `position_ids` json DEFAULT NULL COMMENT 'Applicable position IDs (JSON array)',
    `remark` varchar(500) DEFAULT NULL COMMENT 'Remark',
    `timezone` varchar(50) DEFAULT 'Asia/Shanghai' COMMENT 'Timezone',
    `deleted` tinyint NOT NULL DEFAULT '0' COMMENT 'Deleted flag: 0-Not deleted, 1-Deleted',
    `create_by` varchar(50) DEFAULT NULL COMMENT 'Creator',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    `update_by` varchar(50) DEFAULT NULL COMMENT 'Updater',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_rule_code` (`rule_code`),
    KEY `idx_status` (`status`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Attendance rule table';

-- Attendance group table
CREATE TABLE IF NOT EXISTS `attendance_group` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    `group_name` varchar(100) NOT NULL COMMENT 'Group name',
    `group_code` varchar(50) NOT NULL COMMENT 'Group code',
    `status` tinyint NOT NULL DEFAULT '1' COMMENT 'Status: 0-Disabled, 1-Enabled',
    `rule_id` bigint NOT NULL COMMENT 'Rule ID',
    `schedule_type` tinyint DEFAULT '0' COMMENT 'Schedule type: 0-Normal shift, 1-Rotating shift, 2-Flexible',
    `schedule_data` json DEFAULT NULL COMMENT 'Schedule data (JSON)',
    `manager_id` varchar(50) DEFAULT NULL COMMENT 'Manager user ID',
    `manager_name` varchar(100) DEFAULT NULL COMMENT 'Manager name',
    `dept_ids` json DEFAULT NULL COMMENT 'Department IDs (JSON array)',
    `position_ids` json DEFAULT NULL COMMENT 'Position IDs (JSON array)',
    `user_ids` json DEFAULT NULL COMMENT 'User IDs (JSON array)',
    `checkin_locations` json DEFAULT NULL COMMENT 'Check-in locations (JSON array)',
    `wifi_list` json DEFAULT NULL COMMENT 'WiFi list (JSON array)',
    `allow_remote` tinyint DEFAULT '0' COMMENT 'Allow remote check-in: 0-No, 1-Yes',
    `max_remote_distance` int DEFAULT '100' COMMENT 'Maximum remote distance (meters)',
    `remark` varchar(500) DEFAULT NULL COMMENT 'Remark',
    `deleted` tinyint NOT NULL DEFAULT '0' COMMENT 'Deleted flag: 0-Not deleted, 1-Deleted',
    `create_by` varchar(50) DEFAULT NULL COMMENT 'Creator',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    `update_by` varchar(50) DEFAULT NULL COMMENT 'Updater',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_group_code` (`group_code`),
    KEY `idx_rule_id` (`rule_id`),
    KEY `idx_status` (`status`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Attendance group table';

-- Attendance record table
CREATE TABLE IF NOT EXISTS `attendance_record` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    `user_id` varchar(50) NOT NULL COMMENT 'User ID',
    `user_name` varchar(100) DEFAULT NULL COMMENT 'User name',
    `attendance_date` date NOT NULL COMMENT 'Attendance date',
    `group_id` bigint DEFAULT NULL COMMENT 'Group ID',
    `rule_id` bigint DEFAULT NULL COMMENT 'Rule ID',
    `checkin_time` datetime DEFAULT NULL COMMENT 'Check-in time',
    `checkout_time` datetime DEFAULT NULL COMMENT 'Check-out time',
    `checkin_latitude` decimal(10,8) DEFAULT NULL COMMENT 'Check-in location (latitude)',
    `checkin_longitude` decimal(11,8) DEFAULT NULL COMMENT 'Check-in location (longitude)',
    `checkout_latitude` decimal(10,8) DEFAULT NULL COMMENT 'Check-out location (latitude)',
    `checkout_longitude` decimal(11,8) DEFAULT NULL COMMENT 'Check-out location (longitude)',
    `checkin_address` varchar(500) DEFAULT NULL COMMENT 'Check-in address',
    `checkout_address` varchar(500) DEFAULT NULL COMMENT 'Check-out address',
    `checkin_wifi_mac` varchar(50) DEFAULT NULL COMMENT 'Check-in WiFi MAC',
    `checkout_wifi_mac` varchar(50) DEFAULT NULL COMMENT 'Check-out WiFi MAC',
    `checkin_device_id` varchar(100) DEFAULT NULL COMMENT 'Check-in device ID',
    `checkout_device_id` varchar(100) DEFAULT NULL COMMENT 'Check-out device ID',
    `checkin_ip` varchar(50) DEFAULT NULL COMMENT 'Check-in IP address',
    `checkout_ip` varchar(50) DEFAULT NULL COMMENT 'Check-out IP address',
    `checkin_method` tinyint DEFAULT NULL COMMENT 'Check-in method: 0-GPS, 1-WiFi, 2-Manual, 3-Remote',
    `checkout_method` tinyint DEFAULT NULL COMMENT 'Check-out method: 0-GPS, 1-WiFi, 2-Manual, 3-Remote',
    `status` tinyint DEFAULT '0' COMMENT 'Status: 0-Normal, 1-Late, 2-Leave early, 3-Absent, 4-Overtime, 5-On leave, 6-On business trip',
    `late_minutes` int DEFAULT '0' COMMENT 'Late minutes',
    `leave_early_minutes` int DEFAULT '0' COMMENT 'Leave early minutes',
    `overtime_minutes` int DEFAULT '0' COMMENT 'Overtime minutes',
    `work_hours` decimal(5,2) DEFAULT '0.00' COMMENT 'Work hours',
    `should_work_hours` decimal(5,2) DEFAULT '8.00' COMMENT 'Should work hours',
    `abnormal` tinyint DEFAULT '0' COMMENT 'Is abnormal: 0-No, 1-Yes',
    `abnormal_reason` varchar(500) DEFAULT NULL COMMENT 'Abnormal reason',
    `approval_id` bigint DEFAULT NULL COMMENT 'Approval ID',
    `remark` varchar(500) DEFAULT NULL COMMENT 'Remark',
    `deleted` tinyint NOT NULL DEFAULT '0' COMMENT 'Deleted flag: 0-Not deleted, 1-Deleted',
    `create_by` varchar(50) DEFAULT NULL COMMENT 'Creator',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    `update_by` varchar(50) DEFAULT NULL COMMENT 'Updater',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_user_date` (`user_id`, `attendance_date`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_attendance_date` (`attendance_date`),
    KEY `idx_group_id` (`group_id`),
    KEY `idx_rule_id` (`rule_id`),
    KEY `idx_status` (`status`),
    KEY `idx_checkin_time` (`checkin_time`),
    KEY `idx_checkout_time` (`checkout_time`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Attendance record table';

-- Attendance exception table
CREATE TABLE IF NOT EXISTS `attendance_exception` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    `user_id` varchar(50) NOT NULL COMMENT 'User ID',
    `user_name` varchar(100) DEFAULT NULL COMMENT 'User name',
    `type` tinyint NOT NULL COMMENT 'Application type: 0-Makeup card, 1-Leave, 2-Business trip, 3-Other',
    `application_date` date NOT NULL COMMENT 'Application date',
    `start_time` datetime NOT NULL COMMENT 'Start time',
    `end_time` datetime NOT NULL COMMENT 'End time',
    `reason` text COMMENT 'Reason',
    `attachments` json DEFAULT NULL COMMENT 'Attachment URLs (JSON array)',
    `status` tinyint DEFAULT '0' COMMENT 'Status: 0-Pending, 1-Approved, 2-Rejected, 3-Canceled',
    `approval_id` bigint DEFAULT NULL COMMENT 'Approval ID',
    `approver_id` varchar(50) DEFAULT NULL COMMENT 'Approver ID',
    `approver_name` varchar(100) DEFAULT NULL COMMENT 'Approver name',
    `approval_time` datetime DEFAULT NULL COMMENT 'Approval time',
    `approval_comment` varchar(500) DEFAULT NULL COMMENT 'Approval comment',
    `related_record_ids` json DEFAULT NULL COMMENT 'Related attendance record IDs (JSON array)',
    `dept_id` varchar(50) DEFAULT NULL COMMENT 'Department ID',
    `dept_name` varchar(100) DEFAULT NULL COMMENT 'Department name',
    `process_result` tinyint DEFAULT '0' COMMENT 'Process result: 0-Not processed, 1-Processed, 2-Error',
    `process_message` varchar(500) DEFAULT NULL COMMENT 'Process message',
    `process_time` datetime DEFAULT NULL COMMENT 'Process time',
    `remark` varchar(500) DEFAULT NULL COMMENT 'Remark',
    `deleted` tinyint NOT NULL DEFAULT '0' COMMENT 'Deleted flag: 0-Not deleted, 1-Deleted',
    `create_by` varchar(50) DEFAULT NULL COMMENT 'Creator',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    `update_by` varchar(50) DEFAULT NULL COMMENT 'Updater',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    PRIMARY KEY (`id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_type` (`type`),
    KEY `idx_status` (`status`),
    KEY `idx_application_date` (`application_date`),
    KEY `idx_start_time` (`start_time`),
    KEY `idx_end_time` (`end_time`),
    KEY `idx_approval_id` (`approval_id`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Attendance exception table';

-- Attendance statistics table
CREATE TABLE IF NOT EXISTS `attendance_stat` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
    `user_id` varchar(50) NOT NULL COMMENT 'User ID',
    `user_name` varchar(100) DEFAULT NULL COMMENT 'User name',
    `dept_id` varchar(50) DEFAULT NULL COMMENT 'Department ID',
    `dept_name` varchar(100) DEFAULT NULL COMMENT 'Department name',
    `period_type` tinyint NOT NULL COMMENT 'Stat period type: 0-Daily, 1-Weekly, 2-Monthly, 3-Quarterly, 4-Yearly',
    `start_date` date NOT NULL COMMENT 'Start date',
    `end_date` date NOT NULL COMMENT 'End date',
    `year_month` date DEFAULT NULL COMMENT 'Year and month (for monthly stats)',
    `quarter` tinyint DEFAULT NULL COMMENT 'Quarter (1-4)',
    `year` int DEFAULT NULL COMMENT 'Year',
    `total_work_days` int DEFAULT '0' COMMENT 'Total work days',
    `actual_work_days` int DEFAULT '0' COMMENT 'Actual work days',
    `normal_days` int DEFAULT '0' COMMENT 'Normal days',
    `late_days` int DEFAULT '0' COMMENT 'Late days',
    `leave_early_days` int DEFAULT '0' COMMENT 'Leave early days',
    `absent_days` int DEFAULT '0' COMMENT 'Absent days',
    `overtime_days` int DEFAULT '0' COMMENT 'Overtime days',
    `leave_days` int DEFAULT '0' COMMENT 'Leave days',
    `business_trip_days` int DEFAULT '0' COMMENT 'Business trip days',
    `total_late_minutes` int DEFAULT '0' COMMENT 'Total late minutes',
    `total_leave_early_minutes` int DEFAULT '0' COMMENT 'Total leave early minutes',
    `total_overtime_minutes` int DEFAULT '0' COMMENT 'Total overtime minutes',
    `total_work_hours` decimal(10,2) DEFAULT '0.00' COMMENT 'Total work hours',
    `should_work_hours` decimal(10,2) DEFAULT '0.00' COMMENT 'Should work hours',
    `normal_rate` decimal(5,2) DEFAULT '0.00' COMMENT 'Normal rate (percentage)',
    `overtime_rate` decimal(5,2) DEFAULT '0.00' COMMENT 'Overtime rate (percentage)',
    `attendance_score` decimal(5,2) DEFAULT '0.00' COMMENT 'Attendance score (0-100)',
    `remark` varchar(500) DEFAULT NULL COMMENT 'Remark',
    `is_final` tinyint DEFAULT '0' COMMENT 'Is final: 0-No, 1-Yes',
    `deleted` tinyint NOT NULL DEFAULT '0' COMMENT 'Deleted flag: 0-Not deleted, 1-Deleted',
    `create_by` varchar(50) DEFAULT NULL COMMENT 'Creator',
    `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    `update_by` varchar(50) DEFAULT NULL COMMENT 'Updater',
    `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_user_period` (`user_id`, `period_type`, `start_date`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_dept_id` (`dept_id`),
    KEY `idx_period_type` (`period_type`),
    KEY `idx_start_date` (`start_date`),
    KEY `idx_end_date` (`end_date`),
    KEY `idx_year_month` (`year_month`),
    KEY `idx_year` (`year`),
    KEY `idx_is_final` (`is_final`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Attendance statistics table';

-- Insert default attendance rules
INSERT INTO `attendance_rule` (`rule_name`, `rule_code`, `status`, `work_start_time`, `work_end_time`, `allow_late_minutes`, `allow_leave_early_minutes`, `overtime_rule`, `weekdays`, `remark`) VALUES
('Standard Work Hours', 'STANDARD_9_6', 1, '09:00:00', '18:00:00', 15, 15, 1, '[1,2,3,4,5]', 'Standard 9 AM to 6 PM work hours, Monday to Friday'),
('Flexible Work Hours', 'FLEXIBLE_8', 1, '08:00:00', '17:00:00', 30, 30, 1, '[1,2,3,4,5]', 'Flexible work hours with 1-hour lunch break'),
('Shift Work A', 'SHIFT_A', 1, '08:00:00', '20:00:00', 10, 10, 2, '[1,2,3,4,5,6,7]', '12-hour shift work'),
('Shift Work B', 'SHIFT_B', 1, '20:00:00', '08:00:00', 10, 10, 2, '[1,2,3,4,5,6,7]', 'Night shift work');