apiVersion: v1
kind: Secret
metadata:
  name: ai-oa-secret
  namespace: ai-oa
type: Opaque
stringData:
  DB_PASSWORD: "root123456"
  REDIS_PASSWORD: ""
  JWT_SECRET: "aioa-jwt-secret-key-for-signing-tokens-must-be-at-least-256-bits-long"
  MIMI_API_KEY: ""
  OPENAI_API_KEY: ""
  CLAUDE_API_KEY: ""