-- ================================================================
-- AI-OA IM Module Database Schema
-- ================================================================

-- Conversation table
CREATE TABLE IF NOT EXISTS `im_conversation` (
    `id` VARCHAR(32) NOT NULL COMMENT 'Conversation ID',
    `type` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Type: 1-private, 2-group, 3-channel',
    `name` VARCHAR(100) DEFAULT NULL COMMENT 'Conversation name',
    `avatar` VARCHAR(500) DEFAULT NULL COMMENT 'Avatar URL',
    `owner_id` VARCHAR(32) NOT NULL COMMENT 'Owner/Creator user ID',
    `last_message_id` VARCHAR(32) DEFAULT NULL COMMENT 'Last message ID',
    `last_message_content` VARCHAR(200) DEFAULT NULL COMMENT 'Last message preview',
    `last_message_time` VARCHAR(50) DEFAULT NULL COMMENT 'Last message time',
    `unread_count` INT(11) DEFAULT 0 COMMENT 'Unread count for current user',
    `mute_status` TINYINT(1) DEFAULT 0 COMMENT 'Mute: 0-normal, 1-muted',
    `top_status` TINYINT(1) DEFAULT 0 COMMENT 'Pin: 0-normal, 1-pinned',
    `archive_status` TINYINT(1) DEFAULT 0 COMMENT 'Archive: 0-normal, 1-archived',
    `max_members` INT(11) DEFAULT -1 COMMENT 'Max members, -1 for unlimited',
    `description` VARCHAR(500) DEFAULT NULL COMMENT 'Description',
    `status` TINYINT(1) DEFAULT 1 COMMENT 'Status: 0-closed, 1-active',
    `remark` VARCHAR(500) DEFAULT NULL COMMENT 'Remark',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    `create_by` VARCHAR(32) DEFAULT NULL COMMENT 'Creator',
    `update_by` VARCHAR(32) DEFAULT NULL COMMENT 'Updater',
    `deleted` TINYINT(1) DEFAULT 0 COMMENT 'Deleted flag',
    PRIMARY KEY (`id`),
    KEY `idx_type` (`type`),
    KEY `idx_owner_id` (`owner_id`),
    KEY `idx_status` (`status`),
    KEY `idx_update_time` (`update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='IM Conversation table';

-- Message table
CREATE TABLE IF NOT EXISTS `im_message` (
    `id` VARCHAR(32) NOT NULL COMMENT 'Message ID',
    `conversation_id` VARCHAR(32) NOT NULL COMMENT 'Conversation ID',
    `sender_id` VARCHAR(32) NOT NULL COMMENT 'Sender user ID',
    `sender_nickname` VARCHAR(100) DEFAULT NULL COMMENT 'Sender nickname',
    `sender_avatar` VARCHAR(500) DEFAULT NULL COMMENT 'Sender avatar',
    `type` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Type: 1-text, 2-image, 3-file, 4-audio, 5-video, 6-location, 7-card, 8-system',
    `content` TEXT COMMENT 'Message content',
    `extra` TEXT COMMENT 'Extra data (JSON)',
    `reply_id` VARCHAR(32) DEFAULT NULL COMMENT 'Reply to message ID',
    `reply_content` VARCHAR(100) DEFAULT NULL COMMENT 'Reply content preview',
    `forward_id` VARCHAR(32) DEFAULT NULL COMMENT 'Forward from message ID',
    `at_user_ids` VARCHAR(500) DEFAULT NULL COMMENT 'At user IDs',
    `at_all` TINYINT(1) DEFAULT 0 COMMENT 'At all: 0-no, 1-yes',
    `read_status` TINYINT(1) DEFAULT 0 COMMENT 'Read: 0-unread, 1-read',
    `read_time` VARCHAR(50) DEFAULT NULL COMMENT 'Read time',
    `read_by` VARCHAR(1000) DEFAULT NULL COMMENT 'Read by user IDs',
    `reaction_count` INT(11) DEFAULT 0 COMMENT 'Reaction count',
    `reactions` TEXT COMMENT 'Reactions (JSON)',
    `recall_status` TINYINT(1) DEFAULT 0 COMMENT 'Recall: 0-normal, 1-recalled',
    `recall_time` VARCHAR(50) DEFAULT NULL COMMENT 'Recall time',
    `sender_deleted` TINYINT(1) DEFAULT 0 COMMENT 'Sender deleted: 0-no, 1-yes',
    `msg_status` TINYINT(1) DEFAULT 1 COMMENT 'Status: 0-sending, 1-sent, 2-failed',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Create time',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Update time',
    `create_by` VARCHAR(32) DEFAULT NULL COMMENT 'Creator',
    `update_by` VARCHAR(32) DEFAULT NULL COMMENT 'Updater',
    `deleted` TINYINT(1) DEFAULT 0 COMMENT 'Deleted flag',
    PRIMARY KEY (`id`),
    KEY `idx_conversation_id` (`conversation_id`),
    KEY `idx_sender_id` (`sender_id`),
    KEY `idx_create_time` (`create_time`),
    KEY `idx_sender_deleted` (`sender_deleted`),
    KEY `idx_recall_status` (`recall_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='IM Message table';

-- Conversation member table
CREATE TABLE IF NOT EXISTS `im_conversation_member` (
    `id` VARCHAR(32) NOT NULL COMMENT 'Member ID',
    `conversation_id` VARCHAR(32) NOT NULL COMMENT 'Conversation ID',
    `user_id` VARCHAR(32) NOT NULL COMMENT 'User ID',
    `nickname` VARCHAR(100) DEFAULT NULL COMMENT 'Nickname in conversation',
    `avatar` VARCHAR(500) DEFAULT NULL COMMENT 'Avatar',
    `role` TINYINT(1) DEFAULT 3 COMMENT 'Role: 1-owner, 2-admin, 3-member',
    `join_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'Join time',
    `last_read_msg_id` VARCHAR(32) DEFAULT NULL COMMENT 'Last read message ID',
    `last_read_time` DATETIME DEFAULT NULL COMMENT 'Last read time',
    `unread_count` INT(11) DEFAULT 0 COMMENT 'Unread count',
    `mute_status` TINYINT(1) DEFAULT 0 COMMENT 'Mute: 0-normal, 1-muted',
    `top_status` TINYINT(1) DEFAULT 0 COMMENT 'Pin: 0-normal, 1-pinned',
    `sort_order` INT(11) DEFAULT 0 COMMENT 'Display order',
    `status` TINYINT(1) DEFAULT 1 COMMENT 'Status: 0-disabled, 1-active',
    `leave_time` DATETIME DEFAULT NULL COMMENT 'Leave time',
    `inviter_id` VARCHAR(32) DEFAULT NULL COMMENT 'Inviter user ID',
    `remark` VARCHAR(100) DEFAULT NULL COMMENT 'Remark',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_conversation_user` (`conversation_id`, `user_id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_status` (`status`),
    KEY `idx_conversation_id` (`conversation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='IM Conversation Member table';
