-- 资产分类表
CREATE TABLE IF NOT EXISTS `asset_category` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `category_code` varchar(50) NOT NULL COMMENT '分类编码',
  `category_name` varchar(100) NOT NULL COMMENT '分类名称',
  `category_type` tinyint NOT NULL COMMENT '分类类型：1-固定资产，2-消耗品，3-办公用品',
  `parent_id` bigint DEFAULT '0' COMMENT '父级分类ID',
  `level` tinyint DEFAULT '1' COMMENT '分类级别',
  `sort_order` int DEFAULT '0' COMMENT '排序号',
  `status` tinyint DEFAULT '1' COMMENT '状态：0-禁用，1-启用',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_category_code` (`category_code`),
  KEY `idx_parent_id` (`parent_id`),
  KEY `idx_category_type` (`category_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资产分类表';

-- 资产信息表
CREATE TABLE IF NOT EXISTS `asset_info` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `asset_code` varchar(50) NOT NULL COMMENT '资产编码',
  `asset_name` varchar(200) NOT NULL COMMENT '资产名称',
  `category_id` bigint NOT NULL COMMENT '资产分类ID',
  `model` varchar(100) DEFAULT NULL COMMENT '资产型号',
  `specification` varchar(500) DEFAULT NULL COMMENT '规格参数',
  `manufacturer` varchar(200) DEFAULT NULL COMMENT '生产厂商',
  `supplier` varchar(200) DEFAULT NULL COMMENT '供应商',
  `purchase_date` date DEFAULT NULL COMMENT '购买日期',
  `purchase_price` decimal(10,2) DEFAULT '0.00' COMMENT '购买价格',
  `unit` varchar(20) DEFAULT NULL COMMENT '计量单位',
  `current_quantity` int DEFAULT '0' COMMENT '当前数量',
  `warning_quantity` int DEFAULT '0' COMMENT '预警数量',
  `location` varchar(200) DEFAULT NULL COMMENT '存放位置',
  `responsible_person` varchar(50) DEFAULT NULL COMMENT '负责人',
  `responsible_person_id` varchar(50) DEFAULT NULL COMMENT '负责人ID',
  `asset_status` tinyint DEFAULT '1' COMMENT '资产状态：1-正常，2-领用中，3-维修中，4-报废',
  `status` tinyint DEFAULT '1' COMMENT '状态：0-禁用，1-启用',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_asset_code` (`asset_code`),
  KEY `idx_category_id` (`category_id`),
  KEY `idx_asset_status` (`asset_status`),
  KEY `idx_location` (`location`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资产信息表';

-- 资产操作记录表
CREATE TABLE IF NOT EXISTS `asset_operation` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `asset_id` bigint NOT NULL COMMENT '资产ID',
  `operation_type` tinyint NOT NULL COMMENT '操作类型：1-登记，2-领用，3-归还，4-调拨，5-报废',
  `operation_quantity` int NOT NULL COMMENT '操作数量',
  `before_quantity` int DEFAULT NULL COMMENT '操作前数量',
  `after_quantity` int DEFAULT NULL COMMENT '操作后数量',
  `operator` varchar(50) NOT NULL COMMENT '领用人/调拨人/报废人',
  `operator_id` varchar(50) DEFAULT NULL COMMENT '领用人ID/调拨人ID/报废人ID',
  `department` varchar(100) DEFAULT NULL COMMENT '部门/目标部门',
  `reason` varchar(500) DEFAULT NULL COMMENT '原因说明',
  `approval_status` tinyint DEFAULT '0' COMMENT '审批状态：0-待审批，1-已通过，2-已拒绝',
  `approval_comment` varchar(500) DEFAULT NULL COMMENT '审批意见',
  `operation_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_asset_id` (`asset_id`),
  KEY `idx_operation_type` (`operation_type`),
  KEY `idx_operation_time` (`operation_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资产操作记录表';

-- 资产盘点表
CREATE TABLE IF NOT EXISTS `asset_inventory` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `inventory_no` varchar(50) NOT NULL COMMENT '盘点单号',
  `inventory_name` varchar(200) NOT NULL COMMENT '盘点名称',
  `inventory_scope` tinyint DEFAULT '1' COMMENT '盘点范围：1-全部，2-按分类，3-按位置',
  `category_id` bigint DEFAULT NULL COMMENT '盘点分类ID',
  `location` varchar(200) DEFAULT NULL COMMENT '盘点位置',
  `responsible_person` varchar(50) NOT NULL COMMENT '盘点负责人',
  `responsible_person_id` varchar(50) DEFAULT NULL COMMENT '盘点负责人ID',
  `start_time` datetime DEFAULT NULL COMMENT '盘点开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '盘点结束时间',
  `inventory_status` tinyint DEFAULT '0' COMMENT '盘点状态：0-待开始，1-进行中，2-已完成',
  `total_assets` int DEFAULT '0' COMMENT '资产总数',
  `inventoried_count` int DEFAULT '0' COMMENT '已盘点数',
  `surplus_count` int DEFAULT '0' COMMENT '盘盈数',
  `shortage_count` int DEFAULT '0' COMMENT '盘亏数',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_inventory_no` (`inventory_no`),
  KEY `idx_inventory_status` (`inventory_status`),
  KEY `idx_start_time` (`start_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资产盘点表';

-- 资产标签表
CREATE TABLE IF NOT EXISTS `asset_label` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `label_code` varchar(50) NOT NULL COMMENT '标签编码（唯一标识）',
  `asset_id` bigint NOT NULL COMMENT '资产ID',
  `asset_code` varchar(50) NOT NULL COMMENT '资产编码',
  `asset_name` varchar(200) NOT NULL COMMENT '资产名称',
  `qr_content` text COMMENT '二维码内容',
  `qr_image_path` varchar(500) DEFAULT NULL COMMENT '二维码图片路径',
  `barcode_content` varchar(100) DEFAULT NULL COMMENT '条码内容',
  `barcode_image_path` varchar(500) DEFAULT NULL COMMENT '条码图片路径',
  `template_id` bigint DEFAULT NULL COMMENT '打印模板ID',
  `template_name` varchar(100) DEFAULT NULL COMMENT '打印模板名称',
  `print_time` datetime DEFAULT NULL COMMENT '打印时间',
  `printer` varchar(50) DEFAULT NULL COMMENT '打印人',
  `printer_id` varchar(50) DEFAULT NULL COMMENT '打印人ID',
  `print_status` tinyint DEFAULT '0' COMMENT '打印状态：0-未打印，1-已打印，2-打印失败',
  `print_count` int DEFAULT '0' COMMENT '打印次数',
  `last_print_time` datetime DEFAULT NULL COMMENT '最后打印时间',
  `label_status` tinyint DEFAULT '1' COMMENT '标签状态：0-禁用，1-启用，2-作废',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_label_code` (`label_code`),
  KEY `idx_asset_id` (`asset_id`),
  KEY `idx_asset_code` (`asset_code`),
  KEY `idx_print_status` (`print_status`),
  KEY `idx_label_status` (`label_status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资产标签表';

-- 库存流水表
CREATE TABLE IF NOT EXISTS `stock_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `record_no` varchar(50) NOT NULL COMMENT '流水号（唯一标识）',
  `asset_id` bigint NOT NULL COMMENT '资产ID',
  `asset_code` varchar(50) NOT NULL COMMENT '资产编码',
  `asset_name` varchar(200) NOT NULL COMMENT '资产名称',
  `operation_type` tinyint NOT NULL COMMENT '操作类型：1-入库，2-出库，3-盘点，4-调拨',
  `sub_type` tinyint DEFAULT NULL COMMENT '操作子类型：101-采购入库，102-退货入库，201-销售出库，202-领用出库，203-报废出库',
  `quantity` int NOT NULL COMMENT '操作数量',
  `before_quantity` int DEFAULT NULL COMMENT '操作前数量',
  `after_quantity` int DEFAULT NULL COMMENT '操作后数量',
  `unit_price` decimal(10,2) DEFAULT NULL COMMENT '单价',
  `total_amount` decimal(10,2) DEFAULT NULL COMMENT '总金额',
  `batch_no` varchar(50) DEFAULT NULL COMMENT '批次号',
  `partner` varchar(200) DEFAULT NULL COMMENT '供应商/客户',
  `warehouse` varchar(100) NOT NULL COMMENT '仓库/库位',
  `target_warehouse` varchar(100) DEFAULT NULL COMMENT '目标仓库/库位（调拨时使用）',
  `operator` varchar(50) NOT NULL COMMENT '经办人',
  `operator_id` varchar(50) DEFAULT NULL COMMENT '经办人ID',
  `operation_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
  `scanned_label_code` varchar(50) DEFAULT NULL COMMENT '扫描标签编码',
  `scan_method` tinyint DEFAULT NULL COMMENT '扫描方式：1-扫码枪，2-手机扫码，3-手动输入',
  `approval_status` tinyint DEFAULT '0' COMMENT '审批状态：0-待审批，1-已通过，2-已拒绝',
  `approval_comment` varchar(500) DEFAULT NULL COMMENT '审批意见',
  `related_order_no` varchar(50) DEFAULT NULL COMMENT '关联单据号（如采购单号、销售单号）',
  `status` tinyint DEFAULT '0' COMMENT '状态：0-草稿，1-已确认，2-已作废',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_no` (`record_no`),
  KEY `idx_asset_id` (`asset_id`),
  KEY `idx_asset_code` (`asset_code`),
  KEY `idx_operation_type` (`operation_type`),
  KEY `idx_operation_time` (`operation_time`),
  KEY `idx_warehouse` (`warehouse`),
  KEY `idx_operator` (`operator`),
  KEY `idx_scanned_label_code` (`scanned_label_code`),
  KEY `idx_approval_status` (`approval_status`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='库存流水表';

-- 办公用品申请单表
CREATE TABLE IF NOT EXISTS `office_supply_request` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `request_no` varchar(50) NOT NULL COMMENT '申请单号',
  `applicant_id` varchar(50) NOT NULL COMMENT '申请人ID',
  `applicant_name` varchar(50) NOT NULL COMMENT '申请人姓名',
  `department_id` varchar(50) NOT NULL COMMENT '部门ID',
  `department_name` varchar(100) NOT NULL COMMENT '部门名称',
  `reason` varchar(500) DEFAULT NULL COMMENT '申请原因',
  `request_status` tinyint NOT NULL DEFAULT '0' COMMENT '申请状态：0-草稿，1-待审批，2-审批通过，3-审批拒绝，4-部分领取，5-已全部领取，6-已取消',
  `approver_id` varchar(50) DEFAULT NULL COMMENT '审批人ID',
  `approver_name` varchar(50) DEFAULT NULL COMMENT '审批人姓名',
  `approve_time` datetime DEFAULT NULL COMMENT '审批时间',
  `approve_comment` varchar(500) DEFAULT NULL COMMENT '审批意见',
  `claim_type` tinyint DEFAULT '1' COMMENT '领用方式：1-一次性领取，2-分批领取',
  `total_quantity` int NOT NULL DEFAULT '0' COMMENT '总数量',
  `claimed_quantity` int NOT NULL DEFAULT '0' COMMENT '已领取数量',
  `expected_claim_time` datetime DEFAULT NULL COMMENT '预计领取时间',
  `urgency_level` tinyint DEFAULT '1' COMMENT '紧急程度：1-普通，2-加急，3-紧急',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_request_no` (`request_no`),
  KEY `idx_applicant_id` (`applicant_id`),
  KEY `idx_department_id` (`department_id`),
  KEY `idx_request_status` (`request_status`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='办公用品申请单表';

-- 办公用品申请明细表
CREATE TABLE IF NOT EXISTS `office_supply_item` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `request_id` bigint NOT NULL COMMENT '申请单ID',
  `asset_id` bigint NOT NULL COMMENT '资产ID（办公用品）',
  `asset_code` varchar(50) NOT NULL COMMENT '资产编码',
  `asset_name` varchar(200) NOT NULL COMMENT '资产名称',
  `specification` varchar(500) DEFAULT NULL COMMENT '规格型号',
  `request_quantity` int NOT NULL COMMENT '申请数量',
  `claimed_quantity` int NOT NULL DEFAULT '0' COMMENT '已领取数量',
  `unit_price` decimal(10,2) DEFAULT '0.00' COMMENT '单价',
  `total_price` decimal(10,2) DEFAULT '0.00' COMMENT '总价',
  `inventory_check_status` tinyint DEFAULT '0' COMMENT '库存检查状态：0-未检查，1-库存充足，2-库存不足，3-自动排队',
  `inventory_check_comment` varchar(500) DEFAULT NULL COMMENT '库存检查备注',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_request_id` (`request_id`),
  KEY `idx_asset_id` (`asset_id`),
  KEY `idx_inventory_check_status` (`inventory_check_status`),
  CONSTRAINT `fk_item_request` FOREIGN KEY (`request_id`) REFERENCES `office_supply_request` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='办公用品申请明细表';

-- 办公用品领用记录表
CREATE TABLE IF NOT EXISTS `office_supply_claim` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `claim_no` varchar(50) NOT NULL COMMENT '领用单号',
  `request_id` bigint NOT NULL COMMENT '申请单ID',
  `item_id` bigint NOT NULL COMMENT '申请明细ID',
  `asset_id` bigint NOT NULL COMMENT '资产ID',
  `asset_code` varchar(50) NOT NULL COMMENT '资产编码',
  `asset_name` varchar(200) NOT NULL COMMENT '资产名称',
  `claim_quantity` int NOT NULL COMMENT '领用数量',
  `claimer_id` varchar(50) NOT NULL COMMENT '领用人ID',
  `claimer_name` varchar(50) NOT NULL COMMENT '领用人姓名',
  `claimer_department_id` varchar(50) DEFAULT NULL COMMENT '领用部门ID',
  `claimer_department_name` varchar(100) DEFAULT NULL COMMENT '领用部门名称',
  `claim_time` datetime NOT NULL COMMENT '领用时间',
  `claim_method` tinyint NOT NULL COMMENT '领用方式：1-扫码领用，2-手动领用',
  `claim_qr_code` varchar(500) DEFAULT NULL COMMENT '领用二维码',
  `qr_code_expire_time` datetime DEFAULT NULL COMMENT '二维码失效时间',
  `sign_status` tinyint NOT NULL DEFAULT '0' COMMENT '签收状态：0-待签收，1-已签收，2-已取消',
  `signer` varchar(50) DEFAULT NULL COMMENT '签收人',
  `sign_time` datetime DEFAULT NULL COMMENT '签收时间',
  `warehouse_manager_id` varchar(50) DEFAULT NULL COMMENT '仓库/前台管理员ID',
  `warehouse_manager_name` varchar(50) DEFAULT NULL COMMENT '仓库/前台管理员姓名',
  `claim_location` varchar(200) DEFAULT NULL COMMENT '领用位置',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `create_by` varchar(50) DEFAULT NULL COMMENT '创建人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `update_by` varchar(50) DEFAULT NULL COMMENT '更新人',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_claim_no` (`claim_no`),
  KEY `idx_request_id` (`request_id`),
  KEY `idx_item_id` (`item_id`),
  KEY `idx_claimer_id` (`claimer_id`),
  KEY `idx_claim_time` (`claim_time`),
  KEY `idx_sign_status` (`sign_status`),
  CONSTRAINT `fk_claim_request` FOREIGN KEY (`request_id`) REFERENCES `office_supply_request` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_claim_item` FOREIGN KEY (`item_id`) REFERENCES `office_supply_item` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='办公用品领用记录表';

-- 插入初始化数据
INSERT INTO `asset_category` (`category_code`, `category_name`, `category_type`, `parent_id`, `level`, `sort_order`, `status`, `remark`) VALUES
('ASSET-FIXED', '固定资产', 1, 0, 1, 1, 1, '固定资产分类'),
('ASSET-CONSUMABLE', '消耗品', 2, 0, 1, 2, 1, '消耗品分类'),
('ASSET-OFFICE', '办公用品', 3, 0, 1, 3, 1, '办公用品分类'),
('ASSET-FIXED-EQUIPMENT', '设备类', 1, 1, 2, 1, 1, '设备类固定资产'),
('ASSET-FIXED-FURNITURE', '家具类', 1, 1, 2, 2, 1, '家具类固定资产'),
('ASSET-CONSUMABLE-PAPER', '纸张类', 2, 2, 2, 1, 1, '纸张类消耗品'),
('ASSET-OFFICE-STATIONERY', '文具类', 3, 3, 2, 1, 1, '文具类办公用品');

INSERT INTO `asset_info` (`asset_code`, `asset_name`, `category_id`, `model`, `purchase_price`, `current_quantity`, `warning_quantity`, `location`, `asset_status`, `status`, `remark`) VALUES
('ASSET-001', '笔记本电脑', 4, 'ThinkPad X1 Carbon', 12999.00, 20, 5, 'IT仓库', 1, 1, '高性能笔记本电脑'),
('ASSET-002', '办公桌', 5, '标准办公桌', 1500.00, 50, 10, '办公区', 1, 1, '标准办公桌'),
('ASSET-003', 'A4打印纸', 6, 'A4 80g', 25.00, 100, 20, '文印室', 1, 1, 'A4打印纸'),
('ASSET-004', '签字笔', 7, '黑色0.5mm', 2.50, 500, 100, '文具柜', 1, 1, '黑色签字笔');