-- H2 compatible schema for testing

CREATE TABLE IF NOT EXISTS im_conversation (
    id VARCHAR(32) PRIMARY KEY,
    type INT DEFAULT 1,
    name VARCHAR(100),
    avatar VARCHAR(500),
    owner_id VARCHAR(32) NOT NULL,
    last_message_id VARCHAR(32),
    last_message_content VARCHAR(200),
    last_message_time VARCHAR(50),
    unread_count INT DEFAULT 0,
    mute_status INT DEFAULT 0,
    top_status INT DEFAULT 0,
    archive_status INT DEFAULT 0,
    max_members INT DEFAULT -1,
    description VARCHAR(500),
    status INT DEFAULT 1,
    remark VARCHAR(500),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    create_by VARCHAR(32),
    update_by VARCHAR(32),
    deleted INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS im_message (
    id VARCHAR(32) PRIMARY KEY,
    conversation_id VARCHAR(32) NOT NULL,
    sender_id VARCHAR(32) NOT NULL,
    sender_nickname VARCHAR(100),
    sender_avatar VARCHAR(500),
    type INT DEFAULT 1,
    content TEXT,
    extra TEXT,
    reply_id VARCHAR(32),
    reply_content VARCHAR(100),
    forward_id VARCHAR(32),
    at_user_ids VARCHAR(500),
    at_all INT DEFAULT 0,
    read_status INT DEFAULT 0,
    read_time VARCHAR(50),
    read_by VARCHAR(1000),
    reaction_count INT DEFAULT 0,
    reactions TEXT,
    recall_status INT DEFAULT 0,
    recall_time VARCHAR(50),
    sender_deleted INT DEFAULT 0,
    msg_status INT DEFAULT 1,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    create_by VARCHAR(32),
    update_by VARCHAR(32),
    deleted INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS im_conversation_member (
    id VARCHAR(32) PRIMARY KEY,
    conversation_id VARCHAR(32) NOT NULL,
    user_id VARCHAR(32) NOT NULL,
    nickname VARCHAR(100),
    avatar VARCHAR(500),
    role INT DEFAULT 3,
    join_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_read_msg_id VARCHAR(32),
    last_read_time TIMESTAMP,
    unread_count INT DEFAULT 0,
    mute_status INT DEFAULT 0,
    top_status INT DEFAULT 0,
    sort_order INT DEFAULT 0,
    status INT DEFAULT 1,
    leave_time TIMESTAMP,
    inviter_id VARCHAR(32),
    remark VARCHAR(100)
);
